version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_postgres
    restart: always
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: salesuser
      POSTGRES_PASSWORD: salespass
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d/
      - ../scripts:/scripts
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
